[project]
name = "stock-chart-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.14",
    "finance-datareader>=0.9.96",
    "openai>=1.93.0",
    "pandas>=2.3.0",
    "uvicorn>=0.35.0",
]
